### ISSUE TITLE
IETF CSR attestation

### ISSUE THREAD

**Issue by frumioj** [pkic/remote-key-attestation#22]
Just making you aware of the IETF activities in the area of attestation, which have some crossover involvement with members of the PKIC. 

e.g. https://www.ietf.org/archive/id/draft-ietf-lamps-csr-attestation-01.html

**Comment by primetomas** [comment]
We already link to this from the Standards section of the web page: 
https://pkic.org/remote-key-attestation/resources/

Is there any other changes you think should be done?
