### ISSUE TITLE
Update attestation capabilities for Entrust nShield

### ISSUE THREAD

**Issue by othouvou** [pkic/remote-key-attestation#23]
Seems that Entrust are now offering a [key attestation generation and verification functionality](https://nshielddocs.entrust.com/key-attestation-docs/v1.0.2/intro.html).

The attestation bundle format is JSON and the verifier is a Windows/Linux installable tool.

**Comment by primetomas** [comment]
Thanks. Added this information in https://github.com/pkic/remote-key-attestation/commit/a7455622df2062029f54a550428f5896818f16ac
