### ISSUE TITLE
Azure Managed HSM remote key attestation on the roadmap missing reference

### ISSUE THREAD

**Issue by freedge** [pkic/remote-key-attestation#24]
the doc mentions
> Azure Key Vault
> Azure Managed HSM    Claimed to be on the roadmap

Is there a link to the claim or to the roadmap that could be added to the page?
I raised the same concern on https://feedback.azure.com/d365community/idea/04fa29b4-fd4b-ef11-b4ac-000d3a7b1c7e

**Comment by primetomas** [comment]
I don't have a reference unfortunately, I was told in a conversation.

**Comment by freedge** [comment]
ok! good luck with the initiative
