### ISSUE TITLE
SmartCard-HSM Supports Key Attestation

### ISSUE THREAD

**Issue by CardContact** [pkic/remote-key-attestation#5]
The SmartCard-HSM token supports [Key Attestation](https://www.smartcard-hsm.com/features.html#devaut) using CV-Certificate Requests as defined in [TR-03110](https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03110/tr-03110.html).

Whenever new key pairs (EC or RSA) are generated on a device, the public key is embedded in CV-REQ and signed by the Device Authentication Private Key. The resulting CV-REQ can be processed by most CVC libraries or other SmartCard-HSMs.

Each device has a Device Authentication EC Key Pair that is certified by the Device Issuer CA during production. The Device Issuer CA itself is certified by the SmartCard-HSM Root CA. The Root CA certificate is placed as trust-anchor in the device during production, so that peering SmartCard-HSMs can validate each others public keys.

The key attestation is the basis for P2P ECDH, that is the cryptographic basis for XKEK Key Domains in which key material can migrated between authorized devices.

**Comment by primetomas** [comment]
@CardContact : I don't know why notifications from GitHub hasn't worked. If you can't make a PR, can you provide information here for what to put in each cell in the table. Then I can easily add it.

**Comment by CardContact** [comment]
Created #20 to add the SmartCard-HSM to the list.

For nerds like us, it contains a link to a deep dive into the bits and bytes of remote key attestation in a SmartCard-HSM.

**Comment by primetomas** [comment]
Great PR. Can I convince you to make a PR for a validation page as well? Looks like you have all the information ready in your documentation?
https://pkic.org/remote-key-attestation/validation/
https://github.com/pkic/remote-key-attestation/tree/main/validation

**Comment by CardContact** [comment]
I can certainly do this.

Is the expectation, that a user can do validation on the command line ?

In that case, I'd propose to carry the card generated CVC in a PKCS#10 extension and have some
Java CLI to parse the request, validate the CVC and match the public keys.

That will take a couple of days though...

**Comment by primetomas** [comment]
At this time there is no standard for carrying the generated evidence in a CSR, so this is out of scope.
You can look at the existing articles under validation for what I believe is the expectation today:
- CSR and attestation evidence delivered separately
- parse and validate the attestation
- match the public keys

I.e. ignoring exactly _how_ the attestation is delivered. Once the IETF draft on CSR attestation moves to RFC, that can be worked in at some time.
